### ISSUE TITLE
Expected EOF exception in DMParser

### ISSUE THREAD

**Issue by ike709** [wixoaGit/OpenDream#11]
```
Unhandled exception. System.Exception: Expected EOF
   at OpenDreamShared.Compiler.Parser.Consume(TokenType type, String errorMessage) in C:\Users\Ike\Documents\GitHub\OpenDream\OpenDream\OpenDreamShared\Compiler\Parser.cs:line 62
   at OpenDreamShared.Compiler.DM.DMParser.File() in C:\Users\Ike\Documents\GitHub\OpenDream\OpenDream\OpenDreamShared\Compiler\DM\DMParser.cs:line 19
   at DMCompiler.Program.Main(String[] args) in C:\Users\Ike\Documents\GitHub\OpenDream\OpenDream\DMCompiler\Program.cs:line 38
```
Tested the compiler against BeeStation after doing a placeholder `#if` implementation (just `SkipIfBody()`) and fixing the other open issues. Can't figure out which file is the issue after poking around with the debugger.

**Comment by wixoaGit** [comment]
The problem is caused by [line 19 in rust_g.dm](https://github.com/BeeStation/BeeStation-Hornet/blob/4d9c18c09d3f78732f4b0d47d81f3f0e531eb4aa/code/__DEFINES/rust_g.dm#L19)

`/* This comment bypasses grep checks */ /var/__rust_g`

After the preprocessor goes through it the line is left with a space at the beginning of the line, which is an indentation error.
In byond this line without a comment also causes an indentation error, but placing the comment there causes it to compile fine.
