### ISSUE TITLE
Closing verb prompt window crashes client and causes exception on server

### ISSUE THREAD

**Issue by DamianX** [wixoaGit/OpenDream#148]
- Run TestGame
- Use the roll_dice verb
- Press the X to close the prompt window

Client:
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Cannot set Visibility to Visible or call Show, ShowDialog, Close, or WindowInteropHelper.EnsureHandle while a Window is closing.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Window.VerifyNotClosing()
   at System.Windows.Window.InternalClose(Boolean shutdown, Boolean ignoreCancel)
   at System.Windows.Window.Close()
   at OpenDreamClient.Interface.Prompts.PromptWindow.FinishPrompt(DMValueType responseType, Object value) in C:\Users\dm\Source\Repos\OpenDream\OpenDreamClient\Interface\Prompts\PromptWindow.cs:line 66
   at OpenDreamClient.Interface.Prompts.PromptWindow.PromptWindow_Closing(Object sender, EventArgs e) in C:\Users\dm\Source\Repos\OpenDream\OpenDreamClient\Interface\Prompts\PromptWindow.cs:line 58
   at System.Windows.Window.OnClosing(CancelEventArgs e)
   at System.Windows.Window.WmClose()
```

Server:
```
=C# StackTrace=
System.Exception: Value DreamValue(DreamObject, null) was not the expected type of String
   at OpenDreamRuntime.DreamValue.GetValueExpectingType(DreamValueType type) in C:\Users\dm\Source\Repos\OpenDream\OpenDreamRuntime\DreamValue.cs:line 95
   at OpenDreamRuntime.DreamValue.GetValueAsString() in C:\Users\dm\Source\Repos\OpenDream\OpenDreamRuntime\DreamValue.cs:line 99
   at OpenDreamRuntime.Procs.Native.DreamProcNativeRoot.NativeProc_roll(DreamObject instance, DreamObject usr, DreamProcArguments arguments) in C:\Users\dm\Source\Repos\OpenDream\OpenDreamRuntime\Procs\Native\DreamProcNativeRoot.cs:line 1033
   at OpenDreamRuntime.Procs.NativeProc.State.InternalResume() in C:\Users\dm\Source\Repos\OpenDream\OpenDreamRuntime\Procs\NativeProc.cs:line 35
   at OpenDreamRuntime.ProcState.Resume() in C:\Users\dm\Source\Repos\OpenDream\OpenDreamRuntime\DreamThread.cs:line 76
```

**Comment by wixoaGit** [comment]
This was fixed in 20c10767fdf724313976b8c0b70396369ee176ae.

Prompts no longer have a close button. Instead, they have a cancel button if `null` is a valid response to the prompt.
