### ISSUE TITLE
`\ref(object)` isn't supported

### ISSUE THREAD

**Issue by ZeWaka** [wixoaGit/OpenDream#15]
title, something like `"\ref(object)"`

```
Unhandled exception. System.Exception: Invalid token '\' in code\procs\logging.dm
   at DMCompiler.Preprocessor.DMPreprocessor.IncludeFile(String includePath, String file) in C:\Spess\OpenDream\DMCompiler\Preprocessor\DMPreprocessor.cs:line 188
   at DMCompiler.Preprocessor.DMPreprocessor.IncludeFile(String includePath, String file) in C:\Spess\OpenDream\DMCompiler\Preprocessor\DMPreprocessor.cs:line 40
   at DMCompiler.Program.Preprocess(String[] files) in C:\Spess\OpenDream\DMCompiler\Program.cs:line 61
   at DMCompiler.Program.Main(String[] args) in C:\Spess\OpenDream\DMCompiler\Program.cs:line 21
```

**Comment by DamianX** [comment]
The correct form is `\ref[object]` and it appears to have been implemented, somewhat.

**Comment by wixoaGit** [comment]
`"\ref[src]"` is supported. What isn't supported however, is `var/ref = \ref(src)`. The exception in the issue refers to [this line of code](https://github.com/goonstation/goonstation/blob/71f02c177df284fab60061fd0edb2e238ea16b21/code/procs/logging.dm#L141), which uses this.

**Comment by DamianX** [comment]
That code is weird. It LOOKS like the text macro, but it's actually referring to the built-in proc.
`var/ref = \replacetext("testing", "test", "replace")` also works in DM, but there's no reason for that `\` to be there.
Not sure if this should be supported, it looks to me like a quirk of the byond compiler.
