### ISSUE TITLE
`VisitDereference()` is not implemented

### ISSUE THREAD

**Issue by ike709** [wixoaGit/OpenDream#173]
Needed for NTstation

**Comment by ike709** [comment]
```
Unhandled exception. System.NotImplementedException: The method or operation is not implemented.
   at OpenDreamShared.Compiler.DM.DMASTVisitor.VisitDereference(DMASTDereference dereference) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamShared\Compiler\DM\DMAST.cs:line 101
   at OpenDreamShared.Compiler.DM.DMASTDereference.Visit(DMASTVisitor visitor) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamShared\Compiler\DM\DMAST.cs:line 1464
   at DMCompiler.DM.Visitors.DMVisitorObjectBuilder.VisitObjectVarDefinition(DMASTObjectVarDefinition varDefinition) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\Visitors\DMVisitorObjectBuilder.cs:line 60
   at OpenDreamShared.Compiler.DM.DMASTObjectVarDefinition.Visit(DMASTVisitor visitor) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamShared\Compiler\DM\DMAST.cs:line 249
   at DMCompiler.DM.Visitors.DMVisitorObjectBuilder.VisitBlockInner(DMASTBlockInner blockInner) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\Visitors\DMVisitorObjectBuilder.cs:line 32
   at OpenDreamShared.Compiler.DM.DMASTBlockInner.Visit(DMASTVisitor visitor) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamShared\Compiler\DM\DMAST.cs:line 152
   at DMCompiler.DM.Visitors.DMVisitorObjectBuilder.VisitFile(DMASTFile file) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\Visitors\DMVisitorObjectBuilder.cs:line 27
   at OpenDreamShared.Compiler.DM.DMASTFile.Visit(DMASTVisitor visitor) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamShared\Compiler\DM\DMAST.cs:line 140
   at DMCompiler.DM.Visitors.DMVisitorObjectBuilder.BuildObjectTree(DMASTFile astFile) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\Visitors\DMVisitorObjectBuilder.cs:line 15
   at DMCompiler.Program.Compile(List`1 preprocessedTokens) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\Program.cs:line 93
   at DMCompiler.Program.Main(String[] args) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\Program.cs:line 22
```

**Comment by ike709** [comment]
Apparently this is intentional, but it should error instead of throwing.

**Comment by ike709** [comment]
Code: `var/global/last_tick_timeofday = world.timeofday` as a toplevel var
