### ISSUE TITLE
`/tmp/` causes `Type does not exist` exception

### ISSUE THREAD

**Issue by ike709** [wixoaGit/OpenDream#197]
```
Unhandled exception. System.Exception: Type /tmp/atom/movable does not exist
   at DMCompiler.DM.DMObjectTree.GetDMObject(DreamPath path, Boolean createIfNonexistent) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\DMObjectTree.cs:line 34
   at DMCompiler.DM.Expressions.Dereference..ctor(DMExpression expr, DMASTDereference astNode, Boolean includingLast) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\Expressions\Dereference.cs:line 32
   at DMCompiler.DM.Visitors.DMVisitorExpression.VisitDereference(DMASTDereference dereference) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\Visitors\DMVisitorExpression.cs:line 335
   at OpenDreamShared.Compiler.DM.DMASTDereference.Visit(DMASTVisitor visitor) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamShared\Compiler\DM\DMAST.cs:line 1464
   at DMCompiler.DM.DMExpression.Create(DMObject dmObject, DMProc proc, DMASTExpression expression, Nullable`1 inferredPath) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\DMExpression.cs:line 30
   at DMCompiler.DM.Visitors.DMVisitorExpression.VisitAssign(DMASTAssign assign) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\Visitors\DMVisitorExpression.cs:line 126
   at OpenDreamShared.Compiler.DM.DMASTAssign.Visit(DMASTVisitor visitor) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamShared\Compiler\DM\DMAST.cs:line 823
   at DMCompiler.DM.DMExpression.Create(DMObject dmObject, DMProc proc, DMASTExpression expression, Nullable`1 inferredPath) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\DMExpression.cs:line 30
   at DMCompiler.DM.DMExpression.Emit(DMObject dmObject, DMProc proc, DMASTExpression expression, Nullable`1 inferredPath) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\DMExpression.cs:line 35
   at DMCompiler.DM.Visitors.DMVisitorProcBuilder.VisitProcStatementExpression(DMASTProcStatementExpression statement) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\Visitors\DMVisitorProcBuilder.cs:line
51
   at OpenDreamShared.Compiler.DM.DMASTProcStatementExpression.Visit(DMASTVisitor visitor) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamShared\Compiler\DM\DMAST.cs:line 277
   at DMCompiler.DM.Visitors.DMVisitorProcBuilder.VisitProcBlockInner(DMASTProcBlockInner block) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\Visitors\DMVisitorProcBuilder.cs:line 46
   at OpenDreamShared.Compiler.DM.DMASTProcBlockInner.Visit(DMASTVisitor visitor) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamShared\Compiler\DM\DMAST.cs:line 164
   at DMCompiler.DM.Visitors.DMVisitorProcBuilder.VisitProcStatementIf(DMASTProcStatementIf statement) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\Visitors\DMVisitorProcBuilder.cs:line 131
   at OpenDreamShared.Compiler.DM.DMASTProcStatementIf.Visit(DMASTVisitor visitor) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamShared\Compiler\DM\DMAST.cs:line 400
   at DMCompiler.DM.Visitors.DMVisitorProcBuilder.VisitProcBlockInner(DMASTProcBlockInner block) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\Visitors\DMVisitorProcBuilder.cs:line 46
   at OpenDreamShared.Compiler.DM.DMASTProcBlockInner.Visit(DMASTVisitor visitor) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamShared\Compiler\DM\DMAST.cs:line 164
   at DMCompiler.DM.Visitors.DMVisitorProcBuilder.VisitProcDefinition(DMASTProcDefinition procDefinition) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\Visitors\DMVisitorProcBuilder.cs:line 38
   at OpenDreamShared.Compiler.DM.DMASTProcDefinition.Visit(DMASTVisitor visitor) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamShared\Compiler\DM\DMAST.cs:line 209
   at DMCompiler.DM.DMProc.Compile(DMObject dmObject) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\DMProc.cs:line 58
   at DMCompiler.DM.DMObject.CompileProcs() in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\DMObject.cs:line 37
   at DMCompiler.DM.Visitors.DMVisitorObjectBuilder.BuildObjectTree(DMASTFile astFile) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\Visitors\DMVisitorObjectBuilder.cs:line 18
   at DMCompiler.Program.Compile(List`1 preprocessedTokens) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\Program.cs:line 93
   at DMCompiler.Program.Main(String[] args) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\Program.cs:line 22

```

**Comment by wixoaGit** [comment]
Fixed by 6ddd1dd79982a5f65c062a0f377fba10ff558139.
