### ISSUE TITLE
WriteSourceAndLine() doesn't always output

### ISSUE THREAD

**Issue by ike709** [wixoaGit/OpenDream#20]
Exception without file info:
```
Unhandled exception. System.Exception: Expected '"' to end string
   at DMCompiler.Preprocessor.DMPreprocessorLexer.LexString(Boolean isLong) in C:\Users\Ike\Documents\GitHub\OpenDream\OpenDream\DMCompiler\Preprocessor\DMPreprocessorLexer.cs:line 233
   at DMCompiler.Preprocessor.DMPreprocessorLexer.ParseNextToken() in C:\Users\Ike\Documents\GitHub\OpenDream\OpenDream\DMCompiler\Preprocessor\DMPreprocessorLexer.cs:line 91
   at OpenDreamShared.Compiler.Lexer.GetNextToken() in C:\Users\Ike\Documents\GitHub\OpenDream\OpenDream\OpenDreamShared\Compiler\Lexer.cs:line 34
   at DMCompiler.Preprocessor.DMPreprocessor.GetNextToken(Boolean ignoreWhitespace) in C:\Users\Ike\Documents\GitHub\OpenDream\OpenDream\DMCompiler\Preprocessor\DMPreprocessor.cs:line 219
   at DMCompiler.Preprocessor.DMPreprocessor.IncludeFile(String includePath, String file) in C:\Users\Ike\Documents\GitHub\OpenDream\OpenDream\DMCompiler\Preprocessor\DMPreprocessor.cs:line 191
   at DMCompiler.Preprocessor.DMPreprocessor.IncludeFile(String includePath, String file) in C:\Users\Ike\Documents\GitHub\OpenDream\OpenDream\DMCompiler\Preprocessor\DMPreprocessor.cs:line 40
   at DMCompiler.Program.Preprocess(String[] files) in C:\Users\Ike\Documents\GitHub\OpenDream\OpenDream\DMCompiler\Program.cs:line 61
   at DMCompiler.Program.Main(String[] args) in C:\Users\Ike\Documents\GitHub\OpenDream\OpenDream\DMCompiler\Program.cs:line 21
```

**Comment by ike709** [comment]
(This is caused by #10 and https://github.com/BeeStation/BeeStation-Hornet/blob/master/code/game/objects/items/devices/scanners.dm)

**Comment by ike709** [comment]
Pretty sure this can be tossed now that WriteSourceAndLine() got nuked
