### ISSUE TITLE
Exception with globals in `switch()` ranges

### ISSUE THREAD

**Issue by ike709** [wixoaGit/OpenDream#205]
DM code:
```
var/datum/configuration/config = new
/datum/config
    var/health_threshold_dead = -100
```

```
/proc/some_proc()
    switch(health)
				if(100 to INFINITY)
					src.healths.icon_state = "health0"
				if(50 to 100)
					src.healths.icon_state = "health2"
				if(0 to 50)
					src.healths.icon_state = "health3"
				if(-50 to 0)
					src.healths.icon_state = "health4"
				if(config.health_threshold_dead to -50)
					src.healths.icon_state = "health5"
				else
					src.healths.icon_state = "health6"
```
Exception:
```
Unhandled exception. System.Exception: expression DMCompiler.DM.Expressions.Dereference can not be const-evaluated
   at DMCompiler.DM.DMExpression.ToConstant() in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\DMExpression.cs:line 46
   at DMCompiler.DM.DMExpression.Constant(DMObject dmObject, DMProc proc, DMASTExpression expression) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\DMExpression.cs:line 41
   at DMCompiler.DM.Visitors.DMVisitorProcBuilder.VisitProcStatementSwitch(DMASTProcStatementSwitch statementSwitch) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\Visitors\DMVisitorProcBuilder.cs:line 28
3
   at OpenDreamShared.Compiler.DM.DMASTProcStatementSwitch.Visit(DMASTVisitor visitor) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamShared\Compiler\DM\DMAST.cs:line 538
   at DMCompiler.DM.Visitors.DMVisitorProcBuilder.VisitProcBlockInner(DMASTProcBlockInner block) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\Visitors\DMVisitorProcBuilder.cs:line 46
   at OpenDreamShared.Compiler.DM.DMASTProcBlockInner.Visit(DMASTVisitor visitor) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamShared\Compiler\DM\DMAST.cs:line 164
   at DMCompiler.DM.Visitors.DMVisitorProcBuilder.VisitProcStatementIf(DMASTProcStatementIf statement) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\Visitors\DMVisitorProcBuilder.cs:line 141
   at OpenDreamShared.Compiler.DM.DMASTProcStatementIf.Visit(DMASTVisitor visitor) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamShared\Compiler\DM\DMAST.cs:line 400
   at DMCompiler.DM.Visitors.DMVisitorProcBuilder.VisitProcBlockInner(DMASTProcBlockInner block) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\Visitors\DMVisitorProcBuilder.cs:line 46
   at OpenDreamShared.Compiler.DM.DMASTProcBlockInner.Visit(DMASTVisitor visitor) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamShared\Compiler\DM\DMAST.cs:line 164
   at DMCompiler.DM.Visitors.DMVisitorProcBuilder.VisitProcStatementIf(DMASTProcStatementIf statement) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\Visitors\DMVisitorProcBuilder.cs:line 131
   at OpenDreamShared.Compiler.DM.DMASTProcStatementIf.Visit(DMASTVisitor visitor) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamShared\Compiler\DM\DMAST.cs:line 400
   at DMCompiler.DM.Visitors.DMVisitorProcBuilder.VisitProcBlockInner(DMASTProcBlockInner block) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\Visitors\DMVisitorProcBuilder.cs:line 46
   at OpenDreamShared.Compiler.DM.DMASTProcBlockInner.Visit(DMASTVisitor visitor) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamShared\Compiler\DM\DMAST.cs:line 164
   at DMCompiler.DM.Visitors.DMVisitorProcBuilder.VisitProcDefinition(DMASTProcDefinition procDefinition) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\Visitors\DMVisitorProcBuilder.cs:line 38
   at OpenDreamShared.Compiler.DM.DMASTProcDefinition.Visit(DMASTVisitor visitor) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamShared\Compiler\DM\DMAST.cs:line 209
   at DMCompiler.DM.DMProc.Compile(DMObject dmObject) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\DMProc.cs:line 58
   at DMCompiler.DM.DMObject.CompileProcs() in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\DMObject.cs:line 37
   at DMCompiler.DM.Visitors.DMVisitorObjectBuilder.BuildObjectTree(DMASTFile astFile) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\Visitors\DMVisitorObjectBuilder.cs:line 18
   at DMCompiler.Program.Compile(List`1 preprocessedTokens) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\Program.cs:line 93
   at DMCompiler.Program.Main(String[] args) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\Program.cs:line 22

```

**Comment by ike709** [comment]
Actually consts don't seem to work in switches either, just like... in general:
```
var/const/whatever = 2
/proc/main()
    var/thing = 2
    switch(thing)
        if(whatever)
```
```
Unhandled exception. System.Exception: expression DMCompiler.DM.Expressions.Field can not be const-evaluated
   at DMCompiler.DM.DMExpression.ToConstant() in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\DMExpression.cs:line 46
   at DMCompiler.DM.DMExpression.Constant(DMObject dmObject, DMProc proc, DMASTExpression expression) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\DMExpression.cs:line 41
   at DMCompiler.DM.Visitors.DMVisitorProcBuilder.VisitProcStatementSwitch(DMASTProcStatementSwitch statementSwitch) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\Visitors\DMVisitorProcBuilder.cs:line 29
0
   at OpenDreamShared.Compiler.DM.DMASTProcStatementSwitch.Visit(DMASTVisitor visitor) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamShared\Compiler\DM\DMAST.cs:line 538
   at DMCompiler.DM.Visitors.DMVisitorProcBuilder.VisitProcBlockInner(DMASTProcBlockInner block) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\Visitors\DMVisitorProcBuilder.cs:line 46
   at OpenDreamShared.Compiler.DM.DMASTProcBlockInner.Visit(DMASTVisitor visitor) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamShared\Compiler\DM\DMAST.cs:line 164
   at DMCompiler.DM.Visitors.DMVisitorProcBuilder.VisitProcDefinition(DMASTProcDefinition procDefinition) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\Visitors\DMVisitorProcBuilder.cs:line 38
   at OpenDreamShared.Compiler.DM.DMASTProcDefinition.Visit(DMASTVisitor visitor) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamShared\Compiler\DM\DMAST.cs:line 209
   at DMCompiler.DM.DMProc.Compile(DMObject dmObject) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\DMProc.cs:line 58
   at DMCompiler.DM.DMObject.CompileProcs() in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\DMObject.cs:line 37
   at DMCompiler.DM.Visitors.DMVisitorObjectBuilder.BuildObjectTree(DMASTFile astFile) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\Visitors\DMVisitorObjectBuilder.cs:line 18
   at DMCompiler.Program.Compile(List`1 preprocessedTokens) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\Program.cs:line 93
   at DMCompiler.Program.Main(String[] args) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\Program.cs:line 22
```

**Comment by wixoaGit** [comment]
This is already reported in issue #52.
