### ISSUE TITLE
User-defined toplevel types do not have a `type` var

### ISSUE THREAD

**Issue by ike709** [wixoaGit/OpenDream#213]
```
Unhandled exception. System.Exception: Invalid property "type" on type /node
   at DMCompiler.DM.Expressions.Dereference..ctor(DMExpression expr, DMASTDereference astNode, Boolean includingLast) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\Expressions\Dereference.cs:line 32
   at DMCompiler.DM.Visitors.DMVisitorExpression.VisitDereference(DMASTDereference dereference) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\Visitors\DMVisitorExpression.cs:line 335
   at OpenDreamShared.Compiler.DM.DMASTDereference.Visit(DMASTVisitor visitor) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamShared\Compiler\DM\DMAST.cs:line 1464
   at DMCompiler.DM.DMExpression.Create(DMObject dmObject, DMProc proc, DMASTExpression expression, Nullable`1 inferredPath) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\DMExpression.cs:line 30
   at DMCompiler.DM.Visitors.DMVisitorExpression.VisitStringFormat(DMASTStringFormat stringFormat) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\Visitors\DMVisitorExpression.cs:line 56
   at OpenDreamShared.Compiler.DM.DMASTStringFormat.Visit(DMASTVisitor visitor) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamShared\Compiler\DM\DMAST.cs:line 691
   at DMCompiler.DM.DMExpression.Create(DMObject dmObject, DMProc proc, DMASTExpression expression, Nullable`1 inferredPath) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\DMExpression.cs:line 30
   at DMCompiler.DM.DMExpression.Emit(DMObject dmObject, DMProc proc, DMASTExpression expression, Nullable`1 inferredPath) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\DMExpression.cs:line 35
   at DMCompiler.DM.Visitors.DMVisitorProcBuilder.VisitProcStatementReturn(DMASTProcStatementReturn statement) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\Visitors\DMVisitorProcBuilder.cs:line 115
   at OpenDreamShared.Compiler.DM.DMASTProcStatementReturn.Visit(DMASTVisitor visitor) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamShared\Compiler\DM\DMAST.cs:line 308
   at DMCompiler.DM.Visitors.DMVisitorProcBuilder.VisitProcBlockInner(DMASTProcBlockInner block) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\Visitors\DMVisitorProcBuilder.cs:line 46
   at OpenDreamShared.Compiler.DM.DMASTProcBlockInner.Visit(DMASTVisitor visitor) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamShared\Compiler\DM\DMAST.cs:line 164
   at DMCompiler.DM.Visitors.DMVisitorProcBuilder.VisitProcDefinition(DMASTProcDefinition procDefinition) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\Visitors\DMVisitorProcBuilder.cs:line 38
   at OpenDreamShared.Compiler.DM.DMASTProcDefinition.Visit(DMASTVisitor visitor) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\OpenDreamShared\Compiler\DM\DMAST.cs:line 209
   at DMCompiler.DM.DMProc.Compile(DMObject dmObject) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\DMProc.cs:line 58
   at DMCompiler.DM.DMObject.CompileProcs() in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\DMObject.cs:line 37
   at DMCompiler.DM.Visitors.DMVisitorObjectBuilder.BuildObjectTree(DMASTFile astFile) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\DM\Visitors\DMVisitorObjectBuilder.cs:line 18
   at DMCompiler.Program.Compile(List`1 preprocessedTokens) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\Program.cs:line 93
   at DMCompiler.Program.Main(String[] args) in C:\Users\main\Documents\GitHub\OpenDream\OpenDream\DMCompiler\Program.cs:line 22

```

**Comment by wixoaGit** [comment]
This is because top-level types are not descendants of `/datum` by default.

**Comment by ike709** [comment]
![image](https://user-images.githubusercontent.com/5714543/125170827-eb047980-e17e-11eb-9fca-6c233c2d74bc.png)

Can confirm that toplevels are implicitly datums in byond
