### ISSUE TITLE
Instantiating types with non-initial values throws an exception

### ISSUE THREAD

**Issue by ike709** [wixoaGit/OpenDream#34]
Example code:
`new /obj/item/weapon/pipe{ ptype = 0 }(src.loc)`

Exception:
```
Unhandled exception. System.Exception: Expected dedent
   at OpenDreamShared.Compiler.Parser`1.Consume(TokenType type, String errorMessage) in C:\Users\Ike\Documents\GitHub\OpenDream\OpenDream\OpenDreamShared\Compiler\Parser.cs:line 67
   at OpenDreamShared.Compiler.DM.DMParser.IndentedProcBlock() in C:\Users\Ike\Documents\GitHub\OpenDream\OpenDream\OpenDreamShared\Compiler\DM\DMParser.cs:line 276
   at OpenDreamShared.Compiler.DM.DMParser.ProcBlock() in C:\Users\Ike\Documents\GitHub\OpenDream\OpenDream\OpenDreamShared\Compiler\DM\DMParser.cs:line 249
[...]
```

**Comment by wixoaGit** [comment]
These are called "modified types", and are described in the docs [here](http://www.byond.com/docs/ref/#/proc/newlist).
