### ISSUE TITLE
Compiler struggles with macro abuse

### ISSUE THREAD

**Issue by AffectedArc07** [wixoaGit/OpenDream#382]
Project: `ParadiseSS13/Paradise` @ `fdc7d2ce71e527cc0b21a530376aa399975fdefb`

Stacktrace:
```
$ ./DMCompiler.exe "C:\Users\AffectedArc07\Documents\Paradise\paradise.dme"
Compiling paradise.dme
Unhandled exception. System.Exception: Invalid token DM_Preproc_TokenConcat(code\modules\maze_generation\maze_generator.dm:67:19, ##x)
   at OpenDreamShared.Compiler.DMPreprocessor.DMPreprocessor.IncludeFile(String includePath, String file) in C:\Users\AffectedArc07\Documents\GitHub\Misc_Shit\OpenDream\OpenDreamShared\Compiler\DMPreprocessor\DMPreprocessor.cs:line 253
   at OpenDreamShared.Compiler.DMPreprocessor.DMPreprocessor.IncludeFile(String includePath, String file) in C:\Users\AffectedArc07\Documents\GitHub\Misc_Shit\OpenDream\OpenDreamShared\Compiler\DMPreprocessor\DMPreprocessor.cs:line 65
   at DMCompiler.Program.Preprocess(List`1 files) in C:\Users\AffectedArc07\Documents\GitHub\Misc_Shit\OpenDream\DMCompiler\Program.cs:line 106
   at DMCompiler.Program.Main(String[] args) in C:\Users\AffectedArc07\Documents\GitHub\Misc_Shit\OpenDream\DMCompiler\Program.cs:line 28
```

Offending code:
```dm
#define LOG_MAZE_PROGRESS(proc2run, opname) \
do { \
    var/timer = start_watch(); \
    proc2run ;\
    log_debug("\[MAZE] Operation '[opname]' on maze at [##x],[##y],[##z] took [stop_watch(timer)]s"); \
} while (FALSE)
```
Note: This is a total abuse of macros but works in DM so here we are. Ike told me to.

**Comment by ike709** [comment]
Note that this same code runs fine without `##`, but BYOND copes with it so OD needs to.

**Comment by ZeWaka** [comment]
how is this abuse, this is literally a normal documented part of the preprocessor

**Comment by ike709** [comment]
@ZeWaka well the actual issue here is that they're not args

**Comment by AffectedArc07** [comment]
> how is this abuse, this is literally a normal [documented](https://spacestation13.github.io/DMByExample/preprocessor/advancedpre.html) part of the preprocessor

`A parameter preceded by ## in the macro body is substituted directly, without any spaces`

This isnt a parameter.

**Comment by wixoaGit** [comment]
Some testing with BYOND's compiler shows that any instance of `##nonexistant_parameter` is just replaced with `nonexistant_parameter`

**Comment by Hinaichigo** [comment]
I encountered a similar error trying to compile
`vgstation13-coders/vgsation13` @ `c8fe2e1e992a46300819859aad2e747702dc6ac1`.

```
Unhandled exception. System.Exception: Invalid token DM_Preproc_ParameterStringify(code\__HELPERS\game.dm:206:2, #)
   at DMCompiler.Compiler.DMPreprocessor.DMPreprocessor.IncludeFile(String includePath, String file) in C:\[...]\OpenDream\DMCompiler\Compiler\DMPreprocessor\DMPreprocessor.cs:line 279
   at DMCompiler.Compiler.DMPreprocessor.DMPreprocessor.IncludeFile(String includePath, String file) in C:\[...]\OpenDream\DMCompiler\Compiler\DMPreprocessor\DMPreprocessor.cs:line 85
   at DMCompiler.DMCompiler.Preprocess(List`1 files) in C:\[...]\OpenDream\DMCompiler\DMCompiler.cs:line 109
   at DMCompiler.DMCompiler.Compile(DMCompilerSettings settings) in C:\[...]\OpenDream\DMCompiler\DMCompiler.cs:line 41
   at DMCompiler.Program.Main(String[] args) in C:\[...]\OpenDream\DMCompiler\Program.cs:line 12
```
The relevant code is:
```
202 #ifdef DEBUG_ROLESELECT
203 #define roleselect_debug(x) testing(x)
204 #warn DEBUG_ROLESELECT is defined!
205 #else
206 # define roleselect_debug(x)
206 #endif
```
