### ISSUE TITLE
Invalid token with macro conditional indentation

### ISSUE THREAD

**Issue by Hinaichigo** [wixoaGit/OpenDream#682]
I encountered an error trying to compile
`vgstation13-coders/vgstation13` @ `c8fe2e1e992a46300819859aad2e747702dc6ac1`:
```
Unhandled exception. System.Exception: Invalid token DM_Preproc_ParameterStringify(code\__HELPERS\game.dm:206:2, #)
   at DMCompiler.Compiler.DMPreprocessor.DMPreprocessor.IncludeFile(String includePath, String file) in C:\[...]\OpenDream\DMCompiler\Compiler\DMPreprocessor\DMPreprocessor.cs:line 279
   at DMCompiler.Compiler.DMPreprocessor.DMPreprocessor.IncludeFile(String includePath, String file) in C:\[...]\OpenDream\DMCompiler\Compiler\DMPreprocessor\DMPreprocessor.cs:line 85
   at DMCompiler.DMCompiler.Preprocess(List`1 files) in C:\[...]\OpenDream\DMCompiler\DMCompiler.cs:line 109
   at DMCompiler.DMCompiler.Compile(DMCompilerSettings settings) in C:\[...]\OpenDream\DMCompiler\DMCompiler.cs:line 41
   at DMCompiler.Program.Main(String[] args) in C:\[...]\OpenDream\DMCompiler\Program.cs:line 12
```
The relevant code is:
```
202 #ifdef DEBUG_ROLESELECT
203 #define roleselect_debug(x) testing(x)
204 #warn DEBUG_ROLESELECT is defined!
205 #else
206 # define roleselect_debug(x)
206 #endif
```
It seems like it has something to do with the indentation after the `#` causing the `define` to not be recognized properly.

**Comment by ike709** [comment]
Until https://github.com/wixoaGit/OpenDream/pull/426 is merged you shouldn't really bother reporting preproc issues.

**Comment by wixoaGit** [comment]
It's still useful to know what the current shortcomings are, and to have more things to test against a preproc refactor.
